[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "project_4_build_agent"
version = "0.0.1"
description = "Make faster reports with agent"
authors = [
  { name = "Your name (or your organization/company/team)" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "aiosqlite>=0.20.0",
    "openai>=2.30.0",
    "pip",
    "python-dotenv",
    "ruff",
    "sqlalchemy[asyncio]",
    "sqlglot>=30.2.1",
    "pytest-repeat>=0.9.4",
]
requires-python = ">=3.10.0"

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23.0",
    "pytest-mock>=3.14",
]

[tool.setuptools.packages]
find = {where = ["src"]}

[tool.ruff]
line-length = 88
# Убираем строгое ограничение include, чтобы Ruff видел все файлы в проекте
# Если хочешь оставить ограничения, добавь туда корень и ipynb
include = ["*.py", "src/**/*.py", "**/*.ipynb", "pyproject.toml"]

[tool.ruff.lint]
# "E", "F" - базовые ошибки, "I" - сортировка импортов
select = ["E", "F", "I"] 
extend-select = ["W", "UP"] # Предупреждения и апгрейд синтаксиса

[tool.ruff.lint.isort]
known-first-party = ["project_4_build_agent"]
force-sort-within-sections = true

